### ISSUE TITLE
Quality format by default

### ISSUE THREAD

**Issue by emulsion-io** [AlexAzumi/webp-converter#1]
Hi,

It would be interesting to be able to modify the batch quality of all images added to the queue, or to define a default quality option.

Have a nice day,

Fabrice

**Comment by cirrus3d** [comment]
Just came by to say this as well. This option weould greatly enhance day-to-day work IMHO.

**Comment by AlexAzumi** [comment]
I've been busy with school, but I'm gonna take the time to implement that feature

**Comment by AlexAzumi** [comment]
The feature has been added on the **v1.1.0** release
