### ISSUE TITLE
V1.1.0 corrupted on MacOS

### ISSUE THREAD

**Issue by lowtekluldo** [AlexAzumi/webp-converter#4]
Hi, 
first of all, thanks for this project.
The issue I found is that 1.1.0 Mac version is corrupted and cannot be opened whereas the previous version works fine.
Tested on 2  MacBooks :  M1 Pro / Sonoma 14.6 and M2 / Sonoma 14.5

Do you think you could update the Mac version?
Thanks for your help.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/2724daa9-97d6-40d8-b753-2102120d00fa">

**Comment by AlexAzumi** [comment]
I think is a GitHub Action related issue. Since I don't have a Mac, I cannot test it myself.
Could you test this build and tell me if it works?

https://drive.google.com/file/d/18b6NgndSK0S7H8QYrKqxpQoYaUtP_3Ic/view?usp=drive_link

**Comment by lowtekluldo** [comment]
Thanks for your quick reply, I will try on monday as I won't have access to my Mac during the weekend.
I will let you know as soon as I can.
Thanks again. :)

**Comment by lowtekluldo** [comment]
Hi, sorry for getting back to you juste now, I was not available before.

I just tested what you sent and unfortunately, it doesn't work as it is not a proper app for MacOS (with a .app extension).
Thanks.

**Comment by AlexAzumi** [comment]
> Hi, sorry for getting back to you just now, I was not available before.
> 
> I just tested what you sent and unfortunately, it doesn't work as it is not a proper app for MacOS (with a .app extension). Thanks.

I'm so sorry, I uploaded the wrong file to Drive.

https://drive.google.com/drive/folders/1HzsaqOC-gd5FU-4DKg-RFyfrkiu_-UVp?usp=sharing

These should be the correct files. The folder contains both the Intel based MacOS app and Apple Silicon (both compressed).

**Comment by lowtekluldo** [comment]
Hi, I just downloaded the files you sent (thanks for these :) ) and the Apple Silicon gives me the same message as the one I posted in the first message. However, the x64 works even on a Mac with M2 chip, it must have some kind of legacy compatibility program to ensure old softwares for Intel Macs work on newer Apple Silicon computers.
Thanks again for your kind help. :)

**Comment by AlexAzumi** [comment]
> Hi, I just downloaded the files you sent (thanks for these :) ) and the Apple Silicon gives me the same message as the one I posted in the first message. However, the x64 works even on a Mac with M2 chip, it must have some kind of legacy compatibility program to ensure old softwares for Intel Macs work on newer Apple Silicon computers. Thanks again for your kind help. :)

I'm glad that this compilation works. I will add the x64 binaries to the latest version. For now I won't use the Apple Silicon one, since it requires further investigation.
